Add Levenberg-Marquardt algorithm and modify curve fitting method
yungyuc/bezierfoil pull request #14
Opened 2024-12-01 15:05 UTC by Gene0315

This PR
1. adds Levenberg-Marquardt algorithm
2. revises curve fitting method
3. splits document into chapters
4. adjusts the line length to be consistent with pdf

2024-12-02 14:18 UTC, yungyuc requested changes
Could you please keep all notes in one (original) file?

2024-12-04 15:59 UTC, Gene0315 commented
> Could you please keep all notes in one (original) file?

@yungyuc It's ok. I have already done it. But, can I ask for the reason?
By the way, I still keep the line length (120 characters) consistent with pdf. If you'd like it restored to 74 characters per line, please let me know.

2024-12-05 05:57 UTC, yungyuc requested changes
> > Could you please keep all notes in one (original) file?
> 
> @yungyuc It's ok. I have already done it. But, can I ask for the reason?

A single file makes it easier to edit.  Multiple files make it hard for _everyone_ in a team to track what to change.  It is usually productive to edit a file not exceeding 20k lines.  

> By the way, I still keep the line length (120 characters) consistent with pdf. If you'd like it restored to 74 characters per line, please let me know.

It's OK to change, but not in this PR.  Change of source text formatting is refactoring, and refactoring should always use standalone PRs.

---

- [x] Please revert change of line width from this PR.  Keep only change of contents.  It is OK to change "code" (text) style, but it is considered refactoring.
- [ ] [`L21`](https://github.com/yungyuc/bezierfoil/pull/14/files#diff-b89d7d2901eef4448199c8d7decf665ab81b21f4de95d81d4a83cb50972a78a8R21): Keep title and author formatting in source.

2024-12-05 05:57 UTC, yungyuc commented on foil.tex
> +% (C) 2024 Yung-Yu Chen.  All rights reserved.
Why do you change the position of the copyright line?  It's usually at the beginning of the file.

But you should add your name it it.

2024-12-05 05:57 UTC, yungyuc commented on foil.tex
> +\title{Fit Four-digit NACA Airfoil with Cubic Bezier Curve}
Please keep the title and author formatting.

2024-12-06 16:20 UTC, Gene0315 commented
> * [ ]  Please revert change of line width from this PR.  Keep only change of contents.  It is OK to change "code" (text) style, but it is considered refactoring.
> * [ ]  [`L21`](https://github.com/yungyuc/bezierfoil/pull/14/files#diff-b89d7d2901eef4448199c8d7decf665ab81b21f4de95d81d4a83cb50972a78a8R21): Keep title and author formatting in source.

What I do in this [commit](https://github.com/yungyuc/bezierfoil/pull/14/commits/2309af03ed6eabbc661ed7baa0c2bc7b700f8c85) :
* [ ] revert change of line width. 
* [ ] recover the original title and author formatting.
* [ ] adjust some line width to make it easier to compare the changes. (If I understand correctly, the purpose of this PR is only to see change of contents.)

I'm sorry for causing the inconvenience, and I will open another PR to change the formatting after closing this PR.

2024-12-07 00:57 UTC, yungyuc requested changes
> What I do in this [commit](https://github.com/yungyuc/bezierfoil/pull/14/commits/2309af03ed6eabbc661ed7baa0c2bc7b700f8c85) :
> 
> * [ ]  revert change of line width.
> * [ ]  recover the original title and author formatting.
> * [ ]  adjust some line width to make it easier to compare the changes. (If I understand correctly, the purpose of this PR is only to see change of contents.)

Correct.

> I'm sorry for causing the inconvenience, and I will open another PR to change the formatting after closing this PR.

It's fine.  And it is good to create an issue to track the formatting change.

You can also use a distinct local branch to keep your formatting change right away.  But formatting changes usually conflict with content changes.  If you do them in parallel, it is likely that you will need to resolve a lot of merge/rebase conflicts.

It is a common workflow to edit the contents and format it in batch after a series of editing.  It is usually more productive.

---

- [ ] [`L68`](https://github.com/yungyuc/bezierfoil/pull/14/files#diff-b89d7d2901eef4448199c8d7decf665ab81b21f4de95d81d4a83cb50972a78a8R68): Revert unnecessary formatting change.

2024-12-07 00:57 UTC, yungyuc commented on foil.tex
> +    Leading edge ($x=0, y=0$)
Please revert unnecessary change of blank lines and other minor formatting.

In a PR adding and changing (editing) contents, formatting changes should be avoided.  On the other hand, when changing formatting/typesetting, do not make content change.  Mixing content and formatting changes will make review hard.

This is a principle derived from computer code.

2024-12-07 00:57 UTC, yungyuc commented on foil.tex
> +\begin{figure}[h!]
This typesetting change is fine.

2024-12-07 00:57 UTC, yungyuc commented on foil.tex
> +Levenberg-Marquardt algorithm (LM) is used to solve non-linear least
It's a good summary.  Thanks.

2024-12-07 00:57 UTC, yungyuc commented on foil.tex
> -
Unnecessary change of blank lines (new lines).

2024-12-16 12:32 UTC, yungyuc commented
@Gene0315 It now looks better.  Are you ready for merging?

2024-12-18 12:46 UTC, Gene0315 commented
> @Gene0315 It now looks better. Are you ready for merging?

Yes!

2024-12-19 01:45 UTC, yungyuc approved these changes

2024-12-19 01:46 UTC, merged

2024-12-19 01:46 UTC, yungyuc commented
Please make an explicit global comment for what you want for the next step, including code review, merging, etc.